Hit-Api
chukwuemeka1234/Leaderboard pull request #2
Opened 2021-12-22 20:03 UTC by chukwuemeka1234

**Hi, there**
**Successfully met all the Project requirements**

- [ ] Create a new game with the name of your choice by using the API.
- [ ] Implement the "Refresh" button (receiving data from the API and parsing the JSON).
- [ ] Implement the form "Submit" button (sending data to the API).
- [ ] Use async and await JavaScript features to consume the API.

2021-12-22 21:01 UTC, ZeenatLawal requested changes
Hi @chukwuemeka1234 , 

Great job so far!:clap: :clap:
## To Highlight 🎊 🎊 
- Git flow is followed. ✔️
- PR has a title and summary. ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 21:01 UTC, ZeenatLawal commented on dist/index.html
> +                <input type="text" class="inputs" name="score" id="score" placeholder="Your score" />
- [ ] The app doesn't seem to run beacuse it can't find the action specified in the form tag, kindly modify this and ensure all API calls are made correctly.

2021-12-22 21:01 UTC, ZeenatLawal commented on src/apiData.js
> +  });
- [ ] As stated in the requirements, kindly use `async` and `await` for API functions.

2021-12-22 21:01 UTC, ZeenatLawal commented on src/apiData.js
> +};
- [ ] As stated in the requirements, kindly use `async` and `await` for API functions.

2021-12-23 01:10 UTC, chukwuemeka1234 commented on dist/index.html
> +                <input type="text" class="inputs" name="score" id="score" placeholder="Your score" />
The app is running on my local server. It's not showing me any errors.

2021-12-23 07:51 UTC, omar-labana commented
Hi @chukwuemeka1234, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 08:05 UTC, merged